--- !map:HashWithIndifferentAccess 
tels: "89264489998"
user: houdini
mess: "\xd0\x9a\xd1\x80\xd1\x83\xd0\xbf\xd0\xbd\xd0\xb0\xd1\x8f \xd0\xbe\xd0\xbf\xd0\
  \xb5\xd1\x80\xd0\xb0\xd1\x86\xd0\xb8\xd1\x8f"
fromPhone: E-Bank
pass: "1234567"
